title: Tom's Blog
permalink: /:categories/:title/
author:
  name: Thomas
  email: Xenaden@aliyun.com
description: > # this means to ignore newlines until "show_excerpts:"
  很惭愧，只做了一点微小的工作
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin:
  timezone: Asia/Hong_Kong
  date_format: "%Y %b %d, %R"

  # generate social links in footer
  #social_links:

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - tags.md
 
footer_pages:
 - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
